### ISSUE TITLE
PrivKey Export

### ISSUE THREAD

**Issue by bitstoreuser** [BitStore/BitStore-iOS#8]
##

**Comment by D-32** [comment]
Go to the Settings tab. Then tap on "Private Keys", then on the key you want to export. Now tap the screen to disable the blur. Now you should see the QR code with the private key or bellow that a text you can copy & paste.
Did that work for you?

**Comment by bitstoreuser** [comment]
Thats my problem. No Key is showing up there...I can only Scan another "Key" by tapping +

**Comment by bitstoreuser** [comment]
Damn

Restored iPhone from iCloud Backup and lost keys maybe?

**Comment by D-32** [comment]
The iCloud Backup doesn't contain the keychain where the private keys are stored. If you use iTunes to backup **and encrypt the backup** then the keychain is added.
In an early version I supported sync for the keychain. This sadly caused problems when using BitStore on multiple devices as iCloud only let one key exist and just overwrote the other one.
I'm sorry to hear about your issue. Sadly not much I can do here.

**Comment by bitstoreuser** [comment]
Lost 2 BTC if it did not encrypt by itself..any chance to do that afterwards?

**Comment by bitstoreuser** [comment]
Managed to extract my Keychain Domain from older Backup

Would be fucking awesome if you can help me

**Comment by D-32** [comment]
If you don't encrypt it Apple doesn't include the keychain. With that I mean the option iTunes gives you when exporting.
Any success with your older backup?

**Comment by bitstoreuser** [comment]
Restoring right now
Backup Date is Sept 2014 maybe I´ve luck

**Comment by bitstoreuser** [comment]
Lost them...

**Comment by D-32** [comment]
Closing this now, as I can't do more to help you. Sorry for your issue.
